routes/web.php
<?php

use Illuminate\Support\Facades\Route;

//Admin ruti

Auth::routes();

//Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'middleware' => 'auth', 'namespace' => 'admin'], function () {

    Route::get('dashboard', 'DashboardController@index')->name('admin.dashboard');
    Route::resource('slider','SliderController');
    Route::resource('category','CategoryController');
    Route::resource('post','PostController');
    Route::resource('imagepost','ImagePostController');
    Route::resource('transport','TransportController');
    Route::resource('album','AlbumController');
    Route::resource('imagealbum','ImageAlbumController');

});
//Pocetna
Route::get('/', 'Front\FrontController@index');

//Aranzmani
Route::get('/arazmani', 'Front\FrontController@arazmani');
Route::get('/arazmani/{category}', 'Front\FrontController@show');

//Postoj
Route::get('/postoj/{post}', 'Front\FrontController@postojshow');

//prevoz
Route::get('/prevoz', 'Front\FrontController@prevozindex');
Route::get('/prevoz/{transport}', 'Front\FrontController@prevozshow');

//Uslovi
Route::get('/uslovi', 'Front\FrontController@uslovi');

//album
Route::get('/album', 'Front\FrontController@albumindex');
Route::get('/album/{album}', 'Front\FrontController@albumshow');

//contact
Route::get('/kontakt', 'Front\FrontController@contact');
Route::post('/kontakt', 'Front\FrontController@postcontact')->name('postcontact');

app/ImageAlbum.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ImageAlbum extends Model
{
    protected $table = 'image_album';

    public function album()
    {
        return $this->belongsTo('App\Album');
    }
}

app/Http/Controllers/admin/ImageAlbumController.php
<?php

namespace App\Http\Controllers\admin;

use App\Album;
use App\Http\Controllers\Controller;
use App\ImageAlbum;
use Faker\Provider\Image;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class ImageAlbumController extends Controller
{
    public function index()
    {
        $imagealbum=ImageAlbum::all();

        return view('admin.imagealbum.index',compact('imagealbum'));
    }

    public function create()
    {
        $album=Album::all();

        return view('admin.imagealbum.create',compact('album'));
    }

    public function store(Request $request)
    {
       /* $this->validate($request,[
            'album'=>'required',
            'image'=>'required|mimes:jpeg,jpg,bmp,png',
        ],[

            'image.required' => 'Немате внесено слика',
            'album.required' => 'Немате внесено албум'
        ]);*/
        foreach(request()->file('images') as $file ) {
            $imagealbum = new ImageAlbum();
            $filename = $file->getClientOriginalName();

            if (!file_exists('uploads/imagealbum')){
                mkdir('uploads/imagealbum', 0777, true);
            }
            $file->move('uploads/imagealbum', $filename);

            $imagealbum->album_id=$request->album;
            $imagealbum->image=$filename;

            $imagealbum->save();
        }
        return redirect()->route('imagealbum.index')->with('status', 'Успешно Внесување')->with('status_code', 'success');

    }

    public function destroy($id)
    {
        $imagealbum=ImageAlbum::findOrFail($id);
        if (file_exists('uploads/imagealbum/' . $imagealbum->image)) {
            unlink('uploads/imagealbum/' . $imagealbum->image);
        }
        $imagealbum->delete();

        return redirect()->back()->with('status', 'Успешно бришење')->with('status_code', 'success');
    }
}

resources/views/admin/imagealbum/create.blade.php
@extends('layouts.app')

@section('title','Slider')

@push('css')

@endpush

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    @if ($errors->any())

                        @foreach ($errors->all() as $error)
                            <div class="alert alert-danger">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close" onclick="this.parentElement.style.display='none'">
                                    <i class="material-icons">close</i>
                                </button>
                                <span>
                                         <b> Danger - </b>{{ $error }}
                                        </span>
                            </div>
                        @endforeach

                    @endif
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title ">Додај нови слики</h4>
                        </div>
                        <div class="card-content">
                            <form method="POST" action="{{route('imagealbum.store')}}" enctype="multipart/form-data">
                                @csrf

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label class="bmd-label-floating">Албум:</label>
                                            <select class="form-control " name="album">
                                                <option disabled selected>Одбери</option>
                                                @foreach($album as $albums)
                                                    <option value="{{$albums->id}}">{{$albums->title}}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        <label class="control-label">Слики</label>
                                        <input type="file" name="images[]" multiple>
                                    </div>
                                </div>
                                <a href="{{route('imagealbum.index')}}" class="btn btn-danger">Назад</a>
                                <button type="submit" class="btn btn-primary">Зачувај</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')

@endpush

resources/views/admin/imagealbum/index.blade.php
@extends('layouts.app')

@section('title','Slider')

@push('css')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">
@endpush

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <a href="{{route('imagealbum.create')}}" class="btn btn-info">Креирај Слики за албум</a>

                    @include('layouts.partials.msg')

                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title ">Сите Слики</h4>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table id="table" class="table table-striped table-bordered" style="width:100%">
                                    <thead class="text-primary">

                                    <th>ID</th>

                                    <th>Албум</th>

                                    <th>Слика</th>

                                    <th>Креирано на:</th>

                                    <th>Последна промена на:</th>

                                    <th>Акција:</th>
                                    </thead>
                                    <tbody>
                                    @foreach($imagealbum as $key=>$imagealbums)
                                        <tr>
                                            <input type="hidden" class="id" value="{{$imagealbums->id}}">
                                            <td>
                                                {{$key + 1}}
                                            </td>

                                            <td>
                                                {{$imagealbums->album->title}}
                                            </td>

                                            <td>
                                                <img class="img-responsive img-thumbnail" id="icon"
                                                     src="{{asset('uploads/imagealbum/'.$imagealbums->image)}}"
                                                     style="width: 100px;height: 100px" onclick="image(this)">
                                            </td>

                                            <td>
                                                {{$imagealbums->created_at}}
                                            </td>

                                            <td>
                                                {{$imagealbums->updated_at}}
                                            </td>
                                            <td>
                                                <div class="text-center">
                                                <button type="button" class="btn btn-danger btn-sm button_delete"
                                                        onclick="deleteTag({{$imagealbums->id}})">
                                                    <i class="material-icons">delete</i>
                                                </button>
                                                <form id="delete-form-{{$imagealbums->id}}"
                                                      action="{{route('imagealbum.destroy',$imagealbums->id)}}"
                                                      style="display: none" method="POST">
                                                    @csrf
                                                    @method('DELETE')
                                                    {{--  <button type="button" class="btn btn-danger btn-xs button_delete">delete</button>--}}
                                                </form>
                                                </div>

                                                {{-- onclick="if(confirm('are you sure you want to delete this')){
                                                      event.preventDefault();
                                                      document.getElementById('delete-form-{{$slider->id}}').submit();

                                                      }else{
                                                      event.preventDefault()
                                                      }
                                                      ">--}}

                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@push('scripts')
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#table').DataTable();
        });
    </script>


    <script>
        @if(session('status'))
        Swal.fire({
            type: '{{session('status_code')}}',
            title: '{{session('status')}}',
            confirmButtonText: 'ok'
        });
        @endif
    </script>
    <script>
        function image(img) {
            var src = img.src;
            Swal.fire({
                imageUrl: src,
            });
        }
    </script>
    <script>
        function deleteTag(id) {
            Swal.fire({
                title: 'Потврда за бришење?',
                text: "Доколку избришиш податоците не може да се вратат назад!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Избриши!',
                cancelButtonText: 'Назад!'
            }).then((result) => {
                if (result.value) {
                    event.preventDefault();
                    document.getElementById('delete-form-' + id).submit();
                    /*    Swal.fire(
                            'Deleted!',
                            'Your file has been deleted.',
                            'success'
                        )*/
                } else {
                    Swal.fire({
                            title: "Податоците не се избришани!",
                            type: "success"
                        }
                    )
                }
            })

        }
        </script>
    {{--  <script>
          $(document).ready(function () {
              $.ajaxSetup({
                  headers: {
                      'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                  }
              });

              $('.button_delete').click(function (e) {
                  e.preventDefault();
                  var delete_id = $(this).closest("tr").find('.delete_value').val();

                  Swal.fire({
                      title: 'Are you sure?',
                      text: "You won't be able to revert this!",
                      icon: 'warning',
                      showCancelButton: true,
                      confirmButtonColor: '#3085d6',
                      cancelButtonColor: '#d33',
                      confirmButtonText: 'Yes, delete it!'
                  })

                      .then((Resoult) => {
                          if (Resoult) {
                              var data = {
                                  "_token": $('input[name="_token"]').val(),
                                  "id": delete_id,
                              };
                              $.ajax({
                                  method: 'DELETE',
                                  url: '/admin/slider/' + delete_id,
                                  data: data,
                                  success: function (response) {
                                      swal(response.status, {
                                          type: "success",
                                      })
                                          .then((result) => {
                                              location.reload();
                                          })
                                  }

                              });
                          }
                          else {
                              swal(response.status, {
                                  text:"You did not delete",
                                  type: "danger",
                              });

                          }
                      });
              })
          })
      </script>--}}

@endpush