routes/web.php
<?php

use Illuminate\Support\Facades\Route;

//Admin ruti

Auth::routes();

//Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'middleware' => 'auth', 'namespace' => 'admin'], function () {

    Route::get('dashboard', 'DashboardController@index')->name('admin.dashboard');
    Route::resource('slider','SliderController');
    Route::resource('category','CategoryController');
    Route::resource('post','PostController');
    Route::resource('imagepost','ImagePostController');
    Route::resource('transport','TransportController');
    Route::resource('album','AlbumController');
    Route::resource('imagealbum','ImageAlbumController');

});
//Pocetna
Route::get('/', 'Front\FrontController@index');

//Aranzmani
Route::get('/arazmani', 'Front\FrontController@arazmani');
Route::get('/arazmani/{category}', 'Front\FrontController@show');

//Postoj
Route::get('/postoj/{post}', 'Front\FrontController@postojshow');

//prevoz
Route::get('/prevoz', 'Front\FrontController@prevozindex');
Route::get('/prevoz/{transport}', 'Front\FrontController@prevozshow');

//Uslovi
Route::get('/uslovi', 'Front\FrontController@uslovi');

//album
Route::get('/album', 'Front\FrontController@albumindex');
Route::get('/album/{album}', 'Front\FrontController@albumshow');

//contact
Route::get('/kontakt', 'Front\FrontController@contact');
Route::post('/kontakt', 'Front\FrontController@postcontact')->name('postcontact');

app/Transport.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Transport extends Model
{
    protected $table = 'transport';
}

app/Http/Controllers/admin/TransportController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Transport;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class TransportController extends Controller
{
    public function index()
    {
        $transport = Transport::all();
        return view('admin.transport.index', compact('transport'));
    }


    public function create()
    {
        return view('admin.transport.create');
    }


    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'description' => 'required',
            'image' => 'required|image|mimes:jpg,png,jpeg,gif',

        ],
            [
                'title.required' => 'Немате внесено наслов',
                'description.required' => 'Немате внесено Опис',
                'image.required' => 'Немате внесено слика'
            ]);
        $slug = Str::slug($request->title);

        $image = $request->file('image');
        if (isset($image)) {
            $currentDate = Carbon::now()->toDateString();
            $imageName = $slug . '-' . $currentDate . '-' . uniqid() . '-' . $image->getClientOriginalName();

            if (!file_exists('uploads/transport')) {
                mkdir('uploads/transport', 0777, true);
            }
            $image->move('uploads/transport', $imageName);
        } else {
            $imageName = 'default.png';
        }

        $transport=new Transport();

        $transport->title=$request->title;
        $transport->origin=$request->origin;
        $transport->destination=$request->destination;
        $transport->price=$request->price;
        $transport->description=$request->description;
        $transport->image=$imageName;
        $transport->slug=$slug;

        $transport->save();
        return redirect()->route('transport.index')->with('status', 'Успешно Внесување')->with('status_code', 'success');
    }


    public function edit($id)
    {
        $transport=Transport::findOrFail($id);
        return view('admin.transport.edit',compact('transport'));
    }


    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title' => 'required',
            'description' => 'required',
        ],
            [
                'title.required' => 'Немате внесено наслов',
                'description.required' => 'Немате внесено Опис',
            ]);
        $transport=Transport::findOrFail($id);

        $image=$request->file('image');

        $slug = Str::slug($request->title);


        if(isset($image)){
            $imageName=$slug.'.'.uniqid().'.'.$image->getClientOriginalExtension();
            if(!file_exists('uploads/transport')){
                mkdir('uploads/transport',0777,true);
            }
            unlink('uploads/transport/'.$transport->image);
            $image->move('uploads/transport',$imageName);
        }
        else
        {
            $imageName = $transport->image;
        }
        $transport->title=$request->title;
        $transport->origin=$request->origin;
        $transport->destination=$request->destination;
        $transport->price=$request->price;
        $transport->description=$request->description;
        $transport->image=$imageName;
        $transport->slug=$slug;

        $transport->save();

        return redirect()->route('transport.index')->with('status', 'Успешна промена')->with('status_code', 'success');
    }

    public function destroy($id)
    {
        $transport=Transport::findOrFail($id);
        if (file_exists('uploads/transport/' . $transport->image)) {
            unlink('uploads/transport/' . $transport->image);
        }

        $transport->delete();

        return redirect()->back()->with('status', 'Успешнo бришење')->with('status_code', 'success');
    }
}

resources/views/admin/transport/create.blade.php
@extends('layouts.app')

@section('title','Slider')

@push('css')
    <link href="https://cdn.quilljs.com/1.2.6/quill.snow.css" rel="stylesheet">
@endpush

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    @if ($errors->any())

                        @foreach ($errors->all() as $error)
                            <div class="alert alert-danger">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close" onclick="this.parentElement.style.display='none'">
                                    <i class="material-icons">close</i>
                                </button>
                                <span>
                                         <b> Danger - </b>{{ $error }}
                                        </span>
                            </div>
                        @endforeach

                    @endif
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title ">Додај нов транспорт</h4>
                        </div>
                        <div class="card-content">
                            <form method="POST" action="{{route('transport.store')}}" enctype="multipart/form-data">
                                @csrf

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label class="bmd-label-floating">Наслов</label>
                                            <input type="text" class="form-control" name="title">
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label class="bmd-label-floating">Тргнување од</label>
                                            <input type="text" class="form-control" name="origin">
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label class="bmd-label-floating"> Дестинација</label>
                                            <input type="text" class="form-control" name="destination">
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label class="bmd-label-floating">Цена</label>
                                            <input type="number" class="form-control" name="price">
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label class="bmd-label-floating">Опис</label>
                                            <textarea type="text" class="form-control" name="description">
                                            </textarea>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        <label class="control-label">Слика</label>
                                        <input type="file" name="image">

                                    </div>
                                </div>
                                <a href="{{route('transport.index')}}" class="btn btn-danger">Назад</a>
                                <button type="submit" class="btn btn-primary">Зачувај</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script>tinymce.init({
            selector:'textarea',
            height: 500,
            toolbar: 'undo redo | formatselect | ' +
                'bold italic backcolor forecolor | alignleft aligncenter ' +
                'alignright alignjustify | bullist numlist outdent indent | '
        });</script>--}}
@endpush

resources/views/admin/transport/edit.blade.php
@extends('layouts.app')

@section('title','Slider')

@push('css')

@endpush

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    @if ($errors->any())

                        @foreach ($errors->all() as $error)
                            <div class="alert alert-danger">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close" onclick="this.parentElement.style.display='none'">
                                    <i class="material-icons">close</i>
                                </button>
                                <span>
                                         <b> Danger - </b>{{ $error }}
                                        </span>
                            </div>
                        @endforeach

                    @endif
                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title ">Промена на Слајдер</h4>
                        </div>
                        <div class="card-content">
                            <form method="POST" action="{{route('transport.update',$transport->id)}}" enctype="multipart/form-data">
                                @csrf
                                @method('PUT')
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label class="bmd-label-floating">Наслов</label>
                                            <input type="text" class="form-control" name="title" value="{{$transport->title}}">
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label class="bmd-label-floating">Тргнување од</label>
                                            <input type="text" class="form-control" name="origin" value="{{$transport->origin}}">
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label class="bmd-label-floating">Дестинација</label>
                                            <input type="text" class="form-control" name="destination" value="{{$transport->destination}}">
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label class="bmd-label-floating">Цена</label>
                                            <input type="number" class="form-control" name="price" value="{{$transport->price}}">
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label class="bmd-label-floating">Опис</label>
                                            <textarea type="text" class="form-control" name="description">
                                                {{$transport->description}}
                                            </textarea>


                                        </div>
                                    </div>
                                </div>


                                <div class="row">
                                    <div class="col-md-12">
                                        <label class="control-label">Image</label>
                                        <input type="file" name="image">

                                    </div>
                                </div>
                                <a href="{{route('slider.index')}}" class="btn btn-danger">Назад</a>
                                <button type="submit" class="btn btn-primary">Зачувај</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script>tinymce.init({
            selector:'textarea',
            height: 500,
            toolbar: 'undo redo | formatselect | ' +
                'bold italic backcolor forecolor | alignleft aligncenter ' +
                'alignright alignjustify | bullist numlist outdent indent | '
        });</script>--}}
@endpush

resources/views/admin/transport/index.blade.php
@extends('layouts.app')

@section('title','Slider')

@push('css')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">
    <style>
        .ellipsis {
            max-width:150px;
            text-overflow: ellipsis;
            overflow: hidden;
            white-space: nowrap;
        }
    </style>
@endpush

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <a href="{{route('transport.create')}}" class="btn btn-info">Креирај Транспорт</a>

                    @include('layouts.partials.msg')

                    <div class="card">
                        <div class="card-header card-header-primary">
                            <h4 class="card-title ">Транспорт</h4>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table id="table" class="table table-striped table-bordered" style="width:100%">
                                    <thead class="text-primary">

                                    <th>ID</th>

                                    <th>Наслов</th>

                                    <th>Опис</th>

                                    <th>Tргнувaње од</th>

                                    <th>Дестинација</th>

                                    <th>Цена</th>

                                    <th>Слика</th>

                                    <th>Креирано на:</th>

                                    <th>Последна промена на:</th>

                                    <th>Акција:</th>
                                    </thead>
                                    <tbody>
                                    @foreach($transport as $key=>$transports)
                                        <tr>
                                            <input type="hidden" class="id" value="{{$transports->id}}">
                                            <td>
                                                {{$key + 1}}
                                            </td>

                                            <td>
                                                {{$transports->title}}
                                            </td>

                                            <td class="ellipsis">
                                                {!!$transports->description!!}
                                            </td>

                                            <td>
                                                {{$transports->origin}}
                                            </td>

                                            <td>
                                                {{$transports->destination}}
                                            </td>

                                            <td>
                                                {{$transports->price}}
                                            </td>

                                            <td>
                                                <img class="img-responsive img-thumbnail" id="icon"
                                                     src="{{asset('uploads/transport/'.$transports->image)}}"
                                                     style="width: 100px;height: 100px" onclick="image(this)">
                                            </td>

                                            <td>
                                                {{$transports->created_at}}
                                            </td>

                                            <td>
                                                {{$transports->updated_at}}
                                            </td>
                                            <td>
                                                <a href="{{route('transport.edit',$transports->id)}}"
                                                   class="btn btn-info btn-sm">
                                                    <i class="material-icons">mode_edit</i>
                                                </a>
                                                <button type="button" class="btn btn-danger btn-sm button_delete"
                                                        onclick="deleteTag({{$transports->id}})">
                                                    <i class="material-icons">delete</i>
                                                </button>
                                                <form id="delete-form-{{$transports->id}}"
                                                      action="{{route('transport.destroy',$transports->id)}}"
                                                      style="display: none" method="POST">
                                                    @csrf
                                                    @method('DELETE')
                                                    {{--  <button type="button" class="btn btn-danger btn-xs button_delete">delete</button>--}}
                                                </form>


                                                {{-- onclick="if(confirm('are you sure you want to delete this')){
                                                      event.preventDefault();
                                                      document.getElementById('delete-form-{{$slider->id}}').submit();

                                                      }else{
                                                      event.preventDefault()
                                                      }
                                                      ">--}}

                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@push('scripts')
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#table').DataTable();
        });
    </script>


    <script>
        /*OVA E ZA MSG OD KONTROLER*/
        @if(session('status'))
        Swal.fire({
            type: '{{session('status_code')}}',
            title: '{{session('status')}}',
            confirmButtonText: 'ok'
        });
        @endif
    </script>

    <script>
       /* SLIKATA OD IMAGES DA JA ZGOLEMI ZA DA SE VIDI UBO*/
        function image(img) {
            var src = img.src;
            Swal.fire({
                imageUrl: src,
            });
        }
    </script>
    <script>
        function deleteTag(id) {
         /*   ZA BRISEJNE NA ID DA DAJ POTVRDA*/
            Swal.fire({
                title: 'Потврда за бришење?',
                text: "Доколку избришиш податоците не може да се вратат назад!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Избриши!',
                cancelButtonText: 'Назад!'
            }).then((result) => {
                if (result.value) {
                    event.preventDefault();
                    document.getElementById('delete-form-' + id).submit();
                    /*    Swal.fire(
                            'Deleted!',
                            'Your file has been deleted.',
                            'success'
                        )*/
                } else {
                    Swal.fire({
                            title: "Податоците не се избришани!",
                            type: "success"
                        }
                    )
                }
            })

        }
        </script>
@endpush






    {{--  <script>
          $(document).ready(function () {
              $.ajaxSetup({
                  headers: {
                      'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                  }
              });

              $('.button_delete').click(function (e) {
                  e.preventDefault();
                  var delete_id = $(this).closest("tr").find('.delete_value').val();

                  Swal.fire({
                      title: 'Are you sure?',
                      text: "You won't be able to revert this!",
                      icon: 'warning',
                      showCancelButton: true,
                      confirmButtonColor: '#3085d6',
                      cancelButtonColor: '#d33',
                      confirmButtonText: 'Yes, delete it!'
                  })

                      .then((Resoult) => {
                          if (Resoult) {
                              var data = {
                                  "_token": $('input[name="_token"]').val(),
                                  "id": delete_id,
                              };
                              $.ajax({
                                  method: 'DELETE',
                                  url: '/admin/slider/' + delete_id,
                                  data: data,
                                  success: function (response) {
                                      swal(response.status, {
                                          type: "success",
                                      })
                                          .then((result) => {
                                              location.reload();
                                          })
                                  }

                              });
                          }
                          else {
                              swal(response.status, {
                                  text:"You did not delete",
                                  type: "danger",
                              });

                          }
                      });
              })
          })
      </script>--}}